"""Usage logging, container size

Revision ID: 2de8535ecf45
Revises: 0009f59d1bf3
Create Date: 2024-11-05 17:27:11.612496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de8535ecf45'
down_revision = '0009f59d1bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('shipping_type',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_date', sa.Date(), nullable=False))
        batch_op.drop_column('expected_shipping_date')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_size', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_id_add', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id_delete', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_user_id_add', 'user', ['user_id_add'], ['id'])
        batch_op.create_foreign_key('fk_product_user_id_delete', 'user', ['user_id_delete'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id_delete')
        batch_op.drop_column('user_id_add')
        batch_op.drop_column('container_size')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_shipping_date', sa.DATE(), nullable=False))
        batch_op.drop_column('ship_date')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('shipping_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('shipping_address',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
