"""Decouple product from inventory

Revision ID: 3cf734741272
Revises: 57c65021447d
Create Date: 2024-11-27 08:28:49.665466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf734741272'
down_revision = '57c65021447d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_allocation_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_product_allocation_id', 'product_allocation', ['product_allocation_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('product_allocation_id')

    # ### end Alembic commands ###
