"""Move shipping date to order from order_item

Revision ID: 4c453a48d687
Revises: b5d896d203d2
Create Date: 2024-11-21 17:33:05.368965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c453a48d687'
down_revision = 'b5d896d203d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_date', sa.Date(), nullable=False))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('ship_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_date', sa.DATE(), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_date')

    # ### end Alembic commands ###
