"""Add total cost to invoice

Revision ID: 53f947e1f34c
Revises: 9b9316add120
Create Date: 2024-12-02 01:29:14.754601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f947e1f34c'
down_revision = '9b9316add120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
