"""Add dock date to product

Revision ID: 59aa26f0728d
Revises: eff2448392e3
Create Date: 2024-11-28 13:22:22.267986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59aa26f0728d'
down_revision = 'eff2448392e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dock_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('dock_date')

    # ### end Alembic commands ###
