"""Combined User and Customer tables to reduce redundancy

Revision ID: 63366dcc657e
Revises: 82455c153724
Create Date: 2024-11-07 11:21:56.107284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63366dcc657e'
down_revision = '82455c153724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('customer')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('status')
        batch_op.drop_column('name')

    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.VARCHAR(length=150), nullable=False),
    sa.Column('shipping_address', sa.VARCHAR(length=250), nullable=False),
    sa.Column('billing_address', sa.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='fk_customer_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
