"""Update relationships for order entry subsystem

Revision ID: 971ae563c309
Revises: be6acd314530
Create Date: 2024-11-19 16:30:23.859541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971ae563c309'
down_revision = 'be6acd314530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_order_user', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_order_product', 'product', ['product_id'], ['id'])
        batch_op.drop_column('billing_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_address', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
