"""Add order_id to allocations

Revision ID: 9b9316add120
Revises: 45ce123f7def
Create Date: 2024-12-02 00:34:19.421376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9316add120'
down_revision = '45ce123f7def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_allocation', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
