"""Update shipment model attributes

Revision ID: a28bcd79bdc6
Revises: 15c50565aae9
Create Date: 2024-11-30 08:57:14.096940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28bcd79bdc6'
down_revision = '15c50565aae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('actual_delivery_date', sa.Date(), nullable=False))
        batch_op.drop_column('estimated_date')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('estimated_date', sa.DATE(), nullable=False))
        batch_op.drop_column('actual_delivery_date')
        batch_op.drop_column('estimated_delivery_date')

    # ### end Alembic commands ###
