"""Add line_item_cost to order_item

Revision ID: a87b2458fbb9
Revises: 4c453a48d687
Create Date: 2024-11-22 00:22:49.970352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87b2458fbb9'
down_revision = '4c453a48d687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_item_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('line_item_cost')

    # ### end Alembic commands ###
