"""Enable user backref, addresses to order

Revision ID: afd6d3e93536
Revises: a87b2458fbb9
Create Date: 2024-11-22 00:47:55.526949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd6d3e93536'
down_revision = 'a87b2458fbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
