"""New column in invoice to track days an invoice is overdue

Revision ID: b8e40d904de9
Revises: 53f947e1f34c
Create Date: 2024-12-02 18:44:20.440385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e40d904de9'
down_revision = '53f947e1f34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_overdue', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('days_overdue')

    # ### end Alembic commands ###
