"""Add admin configuration key/value table

Revision ID: be6acd314530
Revises: ee68b3f61950
Create Date: 2024-11-14 16:13:44.749044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6acd314530'
down_revision = 'ee68b3f61950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_status')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('customer_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
