"""Allow date_shipped and delivery_date to be null

Revision ID: c3f131d5efd6
Revises: bcef467f219c
Create Date: 2024-11-24 14:26:43.832530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f131d5efd6'
down_revision = 'bcef467f219c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('date_shipped',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_shipped',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
