"""Allow null for actual_delivery_date

Revision ID: d793a3b298b5
Revises: a28bcd79bdc6
Create Date: 2024-11-30 09:01:18.817328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd793a3b298b5'
down_revision = 'a28bcd79bdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('actual_delivery_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('actual_delivery_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
